name: AOC_2022

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Day 1
      run: |
        cd ./day1
        cargo build --verbose
        cargo test --verbose
        cd ../
    - name: Day 2
      run: |
        cd ./day2
        cargo build --verbose
        cargo test --verbose
        cd ../
    - name: Day 3
      run: |
        cd ./day3
        cargo build --verbose
        cargo test --verbose
        cd ../
    - name: Day 4
      run: |
        cd ./day4
        cargo build --verbose
        cargo test --verbose
        cd ../
    - name: Day 5
      run: |
        cd ./day5
        cargo build --verbose
        cargo test --verbose
        cd ../
    - name: Day 6
      run: |
        cd ./day6
        cargo build --verbose
        cargo test --verbose
        cd ../