name: Build & Test: AOC 2022

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Day 1
      run: |
        cd ./day1
        cargo build --verbose
        cargo test --verbose
        cd ../
